---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bottlerocket
  region: us-west-2
  version: '1.27'

managedNodeGroups:
  - name: ng-bottlerocket
    instanceType: m5.large
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    amiFamily: Bottlerocket
    labels: { role: br-worker }
    tags:
      nodegroup-type: Bottlerocket
    bottlerocket:
      settings:
        motd: "Hello from eksctl!"
    ssh:
      allow: true
      publicKeyName: eks_bottlerocket
